version: '3'

services:
  web:
    image: nginx:latest
    container_name: yii2-app-web
    ports:
      - "8888:80"
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - yii2-network

  php-fpm:
    build:
      context: docker
      dockerfile: php-fpm.Dokerfile
    volumes:
      - ./:/app
    networks:
      - yii2-network

  db:
    image: mysql:5.7
    container_name: yii2-app-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - yii2-network

volumes:
  db-data:

networks:
  yii2-network:
